# Used when Railway service root is set to /backend
[phases.setup]
nixLibs = ["...", "libuuid", "alsa-lib", "openssl"]
aptPkgs = ["...", "libuuid1", "libasound2t64", "libssl3t64", "ca-certificates"]

[start]
cmd = "chmod +x start.sh && ./start.sh"
